const skillsData = [
    { word: 'Angular' },
    { word: 'Next.js' },
    { word: 'Nust.js' },
    { word: '.Net' },
    { word: '.ASP' },
    { word: 'React' },
    { word: 'React-Native' },
    { word: 'Flutter' },
    { word: 'Android' },
    { word: 'Java' },
    { word: 'HTML' },
    { word: 'CSS' },
    { word: 'Jquery' },
    { word: 'Javascript' },
    { word: 'Typescript' },
    { word: 'Bootstrap' },
    { word: 'Node.js' },
    { word: 'Crop Management' },
    { word: 'Horticulture' },
    { word: 'Pest Management' },
    { word: 'Sustainable Farming Practices' },
    { word: 'Architectural Design' },
    { word: 'Building Codes & Safety' },
    { word: 'CAD Software' },
    { word: 'Project Management' },
    { word: 'Urban & City Planning' },
    { word: 'Art Curation' },
    { word: 'Costume Design' },
    { word: 'Direction & Production' },
    { word: 'Performance (Acting, Singing, Dancing)' },
    { word: 'Scriptwriting' },
    { word: 'Set Design' },
    { word: 'Sound & Lighting Design' },
    { word: 'Blueprint Reading' },
    { word: 'Carpentry' },
    { word: 'Equipment Operation' },
    { word: 'Masonry' },
    { word: 'Safety Management' },
    { word: 'Communication' },
    { word: 'Conflict Resolution' },
    { word: 'CRM Software (Zendesk, Zoho Desk)' },
    { word: 'Customer Relationship Management' },
    { word: 'Empathy' },
    { word: 'Patience' },
    { word: 'Adobe Creative Suite' },
    { word: 'Graphic Design' },
    { word: 'Illustration' },
    { word: 'Prototyping' },
    { word: 'User Experience (UX) Design' },
    { word: 'User Interface (UI) Design' },
    { word: 'Web Design' },
    { word: 'Wireframing' },
    { word: 'Customer Service' },
    { word: 'Digital Marketing' },
    { word: 'E-commerce Platform Management (Shopify, WooCommerce)' },
    { word: 'Inventory Management' },
    { word: 'Online Sales' },
    { word: 'Web Analytics' },
    { word: 'Classroom Management' },
    { word: 'Curriculum Development' },
    { word: 'Educational Technology' },
    { word: 'Lesson Planning' },
    { word: 'Special Education' },
    { word: 'Tutoring' },
    { word: 'Energy Efficiency Analysis' },
    { word: 'Energy Policy' },
    { word: 'Maintenance and Repair' },
    { word: 'Chemical Engineering' },
    { word: 'Civil Engineering' },
    { word: 'Electrical Engineering' },
    { word: 'Mechanical Engineering' },
    { word: 'Quality Assurance and Control' },
    { word: 'Conservation' },
    { word: 'Environmental Analysis' },
    { word: 'Environmental Law' },
    { word: 'Renewable Energy Systems' },
    { word: 'Sustainability Planning' },
    { word: 'Waste Management' },
    { word: 'Accounting' },
    { word: 'Budgeting' },
    { word: 'Economic Forecasting' },
    { word: 'Financial Analysis' },
    { word: 'Financial Reporting' },
    { word: 'QuickBooks' },
    { word: 'Tax Preparation' },
    { word: 'Health Education' },
    { word: 'Nutrition Planning' },
    { word: 'Personal Training' },
    { word: 'Physical Therapy' },
    { word: 'Wellness Coaching' },
    { word: 'Yoga or Pilates Instruction' },
    { word: 'Bartending' },
    { word: 'Culinary Skills' },
    { word: 'Food Preparation' },
    { word: 'Food Safety & Hygiene' },
    { word: 'Food Service' },
    { word: 'Menu Development' },
    { word: 'CPR Certified' },
    { word: 'First Aid' },
    { word: 'Healthcare Administration' },
    { word: 'Medical Coding' },
    { word: 'Medical Terminology' },
    { word: 'Nursing' },
    { word: 'Patient Care' },
    { word: 'Cleaning and Sanitation' },
    { word: 'Event Planning & Coordination' },
    { word: 'Food & Beverage Service' },
    { word: 'Guest Services' },
    { word: 'Hotel Management' },
    { word: 'Employee Engagement' },
    { word: 'HR Policies & Procedures' },
    { word: 'Payroll Management' },
    { word: 'Performance Management' },
    { word: 'Talent Acquisition' },
    { word: 'AI and Machine Learning' },
    { word: 'Cloud Computing' },
    { word: 'Cybersecurity' },
    { word: 'Database Management' },
    { word: 'IT Troubleshooting' },
    { word: 'Network Administration' },
    { word: 'Programming' },
    { word: 'Case Management' },
    { word: 'Compliance Management' },
    { word: 'Contract Law' },
    { word: 'Corporate Law' },
    { word: 'Intellectual Property Law' },
    { word: 'Legal Research' },
    { word: 'Order Fulfillment' },
    { word: 'Supply Chain Management' },
    { word: 'Transport Management' },
    { word: 'Warehouse Management' },
    { word: 'Business Development' },
    { word: 'Change Management' },
    { word: 'Decision Making' },
    { word: 'Risk Management' },
    { word: 'Strategic Planning' },
    { word: 'Team Leadership' },
    { word: 'Lean Manufacturing' },
    { word: 'Maintenance Skills' },
    { word: 'Production Planning' },
    { word: 'Quality Control' },
    { word: 'Content Creation' },
    { word: 'Email Marketing' },
    { word: 'Google Analytics' },
    { word: 'Market Research' },
    { word: 'Marketing Strategy' },
    { word: 'Product Marketing' },
    { word: 'Public Relations' },
    { word: 'SEO/SEM' },
    { word: 'Social Media Marketing' },
    { word: 'Broadcast Media' },
    { word: 'Editing' },
    { word: 'Journalism' },
    { word: 'Social Media Management' },
    { word: 'Video Production' },
    { word: 'Emergency Response' },
    { word: 'Equipment Maintenance' },
    { word: 'Leadership' },
    { word: 'Security Management' },
    { word: 'Training & Development' },
    { word: 'Community Outreach' },
    { word: 'Crisis Intervention' },
    { word: 'Fundraising' },
    { word: 'Program Development' },
    { word: 'Volunteer Coordination' },
    { word: 'Community Development' },
    { word: 'Grant Writing' },
    { word: 'Legislative Knowledge' },
    { word: 'Policy Analysis' },
    { word: 'Program Evaluation' },
    { word: 'Property Evaluation' },
    { word: 'Property Management' },
    { word: 'Real Estate Law' },
    { word: 'Real Estate Marketing' },
    { word: 'Merchandising' },
    { word: 'Retail Buying' },
    { word: 'Sales' },
    { word: 'Store Management' },
    { word: 'Visual Merchandising' },
    { word: 'Cold Calling' },
    { word: 'CRM Software (Salesforce, HubSpot)' },
    { word: 'Customer Retention' },
    { word: 'Negotiation' },
    { word: 'Product Knowledge' },
    { word: 'Relationship Building' },
    { word: 'Sales Presentations' },
    { word: 'Sales Strategy' },
    { word: 'Data Analysis' },
    { word: 'Experimental Design' },
    { word: 'Field Research' },
    { word: 'Laboratory Techniques' },
    { word: 'Scientific Writing' },
    { word: 'Statistical Analysis' },
    { word: 'Dispatching' },
    { word: "Driver's Safety" },
    { word: 'Fleet Management' },
    { word: 'Route Planning' },
    { word: 'Vehicle Maintenance' },
    { word: 'Event Planning' },
    { word: 'Guided Tours' },
    { word: 'Hospitality' },
    { word: 'Travel Planning' },
    { word: 'Travel Sales' },
    { word: 'Content Strategy' },
    { word: 'Copywriting' },
    { word: 'Creative Writing' },
    { word: 'Editing & Proofreading' },
    { word: 'SEO Writing' },
    { word: 'Technical Writing' }
];
export default skillsData;
